import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useAuth } from '../features/auth/AuthContext';
import * as db from '../lib/db';
import { uploadBookCover } from '../lib/cloudinary';
import type { Announcement } from '../types';

export default function AdminContentPage() {
  const { username } = useParams(); const { profile } = useAuth();
  const [items, setItems] = useState<Announcement[]>([]); const [type, setType] = useState<'artikel'|'pengumuman'>('artikel');
  const [form, setForm] = useState({ title:'', category:'Literasi', summary:'', cover_image:'' }); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  const load = async () => { setLoading(true); setError(''); try { setItems((await db.fetchAnnouncements()).data); } catch (e) { setError(e instanceof Error ? e.message : 'Konten gagal dimuat.'); } finally { setLoading(false); } };
  useEffect(()=>{void load()},[]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); setMessage(''); try { const saved=await db.insertAnnouncement({...form,author:profile?.nama_lengkap||'Pustakawan',badge:type==='artikel'?'Artikel':'Pengumuman',content_type:type,published:false}); if(!saved)throw new Error('Konten gagal disimpan.'); setForm({title:'',category:'Literasi',summary:'',cover_image:''}); await load(); setMessage(`${type==='artikel'?'Artikel':'Pengumuman'} disimpan sebagai draft.`); } catch(e){setError(e instanceof Error?e.message:'Konten gagal disimpan.')} finally{setBusy(false)} };
  const publish = async (item: Announcement) => { if(!profile?.id)return; setBusy(true);setError('');try{await db.setAnnouncementPublished(item.id,!item.published,profile.id);await load();setMessage(item.published?'Konten dikembalikan menjadi draft.':'Konten diterbitkan.')}catch(e){setError(e instanceof Error?e.message:'Status konten gagal diubah.')}finally{setBusy(false)}};
  const visible=items.filter(item=>item.contentType===type);
  return <div className="admin-page space-y-6"><div><h1 className="text-2xl font-bold">Kelola {type==='artikel'?'Artikel':'Pengumuman'}</h1><p className="mt-1 text-sm text-slate-500">Tulis, simpan sebagai draft, lalu terbitkan saat siap.</p></div><div className="flex gap-2"><button type="button" onClick={()=>setType('artikel')} className={type==='artikel'?'bg-emerald-800 text-white':''}>Artikel</button><button type="button" onClick={()=>setType('pengumuman')} className={type==='pengumuman'?'bg-emerald-800 text-white':''}>Pengumuman</button></div>{error&&<div role="alert" className="rounded-xl bg-rose-50 p-4 text-rose-800">{error}</div>}{message&&<div role="status" className="rounded-xl bg-emerald-50 p-4 text-emerald-900">{message}</div>}<form onSubmit={save}><label>Judul<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Kategori<input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Isi<textarea required rows={7} value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></label><label>Foto<input type="url" value={form.cover_image} onChange={e=>setForm({...form,cover_image:e.target.value})}/></label><label>Unggah foto<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void (async()=>{try{setForm({...form,cover_image:await uploadBookCover(file)})}catch(err){setError(err instanceof Error?err.message:'Foto gagal diunggah.')}})()}}/></label><button disabled={busy}>{busy?'Menyimpan…':'Simpan draft'}</button></form>{loading?<p role="status">Memuat konten…</p>:!visible.length?<p className="rounded-xl border border-dashed p-6 text-slate-500">Belum ada {type}.</p>:<div className="space-y-3">{visible.map(item=><article key={item.id} className="lasem-panel flex items-start justify-between gap-4 p-4"><div><h2 className="font-bold">{item.title}</h2><p className="text-sm text-slate-600">{item.summary}</p><small>{item.published?'Terbit':'Draft'}</small></div><div className="flex gap-2"><Link className="rounded-lg border px-3 py-2 text-sm" to={`/app/${username}/unggah-artikel/edit/${item.id}`}>Edit</Link><button disabled={busy} onClick={()=>void publish(item)}>{item.published?'Sembunyikan':'Terbitkan'}</button></div></article>)}</div>}</div>;
}
