import { useEffect, useState } from 'react';
import { BookOpen, Search, ArrowRight, Sprout, Store, GraduationCap, Landmark, MessageCircle, Feather } from 'lucide-react';
import { Link } from 'react-router-dom';
import * as db from '../lib/db';
import type { Announcement, ForumPost } from '../types';

const services = [
  ['Koleksi Buku Desa', 'Jelajahi buku pertanian, pendidikan, UMKM, budaya, dan bacaan keluarga.', BookOpen],
  ['Peminjaman Buku', 'Ajukan peminjaman buku fisik dan digital dengan alur yang mudah.', Landmark],
  ['Unduhan Offline', 'Simpan bacaan pilihan untuk digunakan saat jaringan terbatas.', ArrowRight],
  ['Usulan Buku', 'Bantu kami melengkapi koleksi sesuai kebutuhan warga.', MessageCircle],
];
const categories = [['Pertanian & Ternak', Sprout], ['UMKM & Keterampilan', Store], ['Edukasi & Sekolah', GraduationCap], ['Budaya & Sejarah', Landmark]];
const news = ['Kelas literasi keluarga Desa Lasem dibuka setiap akhir pekan', 'Koleksi baru panduan tambak dan pertanian tersedia untuk warga', 'Pustakawan desa membuka layanan konsultasi dan usulan buku'];

export default function PublicHomePage() {
  const [announcements, setAnnouncements] = useState<Announcement[]>([]);
  const [posts, setPosts] = useState<ForumPost[]>([]);
  useEffect(() => {
    void Promise.all([db.fetchAnnouncements(true), db.fetchForumPosts()]).then(([a, p]) => {
      setAnnouncements(a.data); setPosts(p);
    }).catch(() => undefined);
  }, []);
  const articles = announcements.filter(a => a.contentType === 'artikel');
  const notices = announcements.filter(a => a.contentType === 'pengumuman');
  return <div className="min-h-screen bg-[#F8F9FA] text-[#1F2937]">
    <header className="bg-[#1E4D3E] text-white sticky top-0 z-30 shadow-md"><div className="max-w-7xl mx-auto px-5 lg:px-8 h-20 flex items-center justify-between gap-6"><Link to="/" className="flex items-center gap-3 shrink-0"><img src="/logo-lasem-mark.png" alt="Perpustakaan Desa Lasem" className="w-14 h-14 rounded-full object-cover bg-white"/><span className="hidden sm:block font-bold leading-tight">PERPUSTAKAAN DESA<br/><span className="text-[#E5A93C]">LASEM</span></span></Link><nav className="hidden lg:flex items-center gap-6 text-sm font-semibold"><a href="#beranda">Beranda</a><a href="#layanan">Layanan</a><a href="#koleksi">Koleksi</a><a href="#kreasi">Kreasi</a><a href="#artikel">Artikel</a><a href="#pengumuman">Pengumuman</a><a href="#tentang">Tentang Kami</a></nav><div className="flex items-center gap-2"><Link to="/register" className="hidden sm:inline-flex border border-white/40 rounded-xl px-4 py-2 text-sm font-semibold hover:bg-white/10">Daftar</Link><Link to="/login" className="bg-[#E5A93C] text-[#1F2937] rounded-xl px-4 py-2 font-bold">Masuk</Link></div></div></header>
    <main>
      <section id="beranda" className="relative overflow-hidden bg-[#F4EFEA]"><div className="max-w-7xl mx-auto px-5 lg:px-8 py-20 lg:py-28 grid lg:grid-cols-2 gap-12 items-center"><div><span className="inline-flex rounded-full bg-[#1E4D3E]/10 text-[#1E4D3E] px-4 py-2 text-sm font-semibold">Simpul Literasi Warga</span><h1 className="mt-5 text-4xl lg:text-6xl font-bold tracking-tight text-[#1B4332]">Membaca, belajar, dan tumbuh bersama Lasem.</h1><p className="mt-5 text-lg text-slate-600 leading-relaxed max-w-xl">Perpustakaan digital dan ruang literasi warga Desa Lasem untuk membuka akses pengetahuan yang dekat, mudah, dan bermanfaat.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/register" className="bg-[#1E4D3E] text-white rounded-xl px-5 py-3 font-bold inline-flex items-center gap-2">Gabung sebagai anggota <ArrowRight className="w-4 h-4"/></Link><Link to="/login" className="bg-white border border-[#1E4D3E]/20 text-[#1E4D3E] rounded-xl px-5 py-3 font-bold">Masuk ke perpustakaan</Link></div></div><div className="bg-[#1E4D3E] rounded-[2rem] p-8 text-white shadow-xl"><div className="flex items-center gap-3"><BookOpen className="w-8 h-8 text-[#E5A93C]"/><span className="text-sm font-semibold text-emerald-100">Koleksi untuk warga</span></div><div className="mt-10 grid grid-cols-2 gap-4"><div className="bg-white/10 rounded-2xl p-5"><strong className="text-3xl">10+</strong><p className="text-sm text-emerald-100 mt-1">Judul siap baca</p></div><div className="bg-white/10 rounded-2xl p-5"><strong className="text-3xl">4</strong><p className="text-sm text-emerald-100 mt-1">Kategori utama</p></div></div><p className="mt-8 text-emerald-100 leading-relaxed">Temukan panduan praktis pertanian, UMKM, buku sekolah, cerita budaya, dan bacaan keluarga.</p></div></div></section>
      <section id="layanan" className="max-w-7xl mx-auto px-5 lg:px-8 py-16"><div className="flex items-end justify-between gap-4 mb-8"><div><p className="text-[#D97706] font-bold text-sm">Layanan kami</p><h2 className="text-3xl font-bold text-[#1B4332]">Perpustakaan yang dekat dengan warga</h2></div><Link to="/register" className="hidden sm:flex items-center gap-1 text-[#1E4D3E] font-semibold">Lihat layanan <ArrowRight className="w-4 h-4"/></Link></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{services.map(([title, desc, Icon]) => <div key={title as string} className="bg-white border border-[#E5E7EB] rounded-2xl p-6 hover:shadow-lg transition"><div className="w-11 h-11 rounded-xl bg-[#1E4D3E]/10 text-[#1E4D3E] grid place-items-center"><Icon className="w-5 h-5"/></div><h3 className="mt-5 font-bold text-lg">{title as string}</h3><p className="mt-2 text-sm text-slate-500 leading-relaxed">{desc as string}</p></div>)}</div></section>
      <section id="koleksi" className="bg-white border-y border-[#E5E7EB]"><div className="max-w-7xl mx-auto px-5 lg:px-8 py-16"><div className="flex items-end justify-between mb-8"><div><p className="text-[#D97706] font-bold text-sm">Jelajahi koleksi</p><h2 className="text-3xl font-bold text-[#1B4332]">Bacaan pilihan untuk berbagai kebutuhan</h2></div><Link to="/koleksi" className="hidden sm:flex items-center gap-1 text-[#1E4D3E] font-semibold">Lihat semua buku <ArrowRight className="w-4 h-4"/></Link></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{categories.map(([label, Icon]) => <Link to={`/koleksi?category=${encodeURIComponent(label as string)}`} key={label as string} className="rounded-2xl bg-[#F4EFEA] p-6 hover:bg-[#1E4D3E] hover:text-white transition"><Icon className="w-7 h-7 text-[#1E4D3E]"/><h3 className="mt-8 font-bold">{label as string}</h3><p className="mt-2 text-sm opacity-70">Koleksi pilihan warga</p></Link>)}</div></div></section>
      <section id="kreasi" className="max-w-7xl mx-auto px-5 lg:px-8 py-16"><p className="text-[#D97706] font-bold text-sm">Warta & Kreasi Warga</p><h2 className="text-3xl font-bold text-[#1B4332] mt-1">Kreasi dari pengguna</h2><div className="mt-8 grid lg:grid-cols-3 gap-5">{posts.map(post=><article key={post.id} className="bg-white border border-[#E5E7EB] rounded-2xl p-6"><span className="text-xs font-semibold text-[#1E4D3E]">{post.category} · {post.author_name}</span><h3 className="mt-3 font-bold text-lg">{post.title}</h3><p className="mt-3 text-sm text-slate-500 whitespace-pre-line">{post.content}</p></article>)}{!posts.length && <p className="text-slate-500">Belum ada kiriman warga.</p>}</div></section>
      <section id="artikel" className="bg-white border-y border-[#E5E7EB] max-w-7xl mx-auto px-5 lg:px-8 py-16"><p className="text-[#D97706] font-bold text-sm">Tulisan admin</p><h2 className="text-3xl font-bold text-[#1B4332] mt-1">Artikel</h2><div className="mt-8 grid lg:grid-cols-3 gap-5">{articles.map(item=><article key={item.id} className="border border-[#E5E7EB] rounded-2xl p-6"><span className="text-xs text-[#1E4D3E]">{item.date} · {item.author}</span><h3 className="mt-3 font-bold text-lg">{item.title}</h3><p className="mt-3 text-sm text-slate-500 whitespace-pre-line">{item.summary}</p></article>)}</div></section>
      <section id="pengumuman" className="max-w-7xl mx-auto px-5 lg:px-8 py-16"><p className="text-[#D97706] font-bold text-sm">Informasi resmi</p><h2 className="text-3xl font-bold text-[#1B4332] mt-1">Pengumuman</h2><div className="mt-8 grid lg:grid-cols-3 gap-5">{notices.map(item=><article key={item.id} className="bg-white border border-[#E5E7EB] rounded-2xl p-6"><span className="text-xs text-[#1E4D3E]">{item.date} · {item.category}</span><h3 className="mt-3 font-bold text-lg">{item.title}</h3><p className="mt-3 text-sm text-slate-500 whitespace-pre-line">{item.summary}</p></article>)}</div></section>
    </main>
    <footer id="tentang" className="bg-[#1B4332] text-white"><div className="max-w-7xl mx-auto px-5 lg:px-8 py-12 grid md:grid-cols-3 gap-10"><div><div className="flex items-center gap-3"><img src="/logo-lasem.png" alt="" className="w-12 h-12 rounded-full bg-white object-cover"/><strong>Perpustakaan Desa Lasem</strong></div><p className="mt-4 text-sm text-emerald-100 leading-relaxed">Simpul literasi warga Desa Lasem, Kecamatan Sidayu, Kabupaten Gresik.</p></div><div><h3 className="font-bold text-[#E5A93C]">Tautan</h3><div className="mt-4 grid gap-2 text-sm text-emerald-100"><a href="#layanan">Layanan</a><a href="#koleksi">Koleksi Buku</a><a href="#berita">Berita</a><Link to="/register">Daftar Anggota</Link></div></div><div><h3 className="font-bold text-[#E5A93C]">Hubungi kami</h3><p className="mt-4 text-sm text-emerald-100">Ruang Baca Desa Lasem<br/>Kecamatan Sidayu, Gresik<br/>WhatsApp pustakawan tersedia setelah masuk.</p></div></div><div className="border-t border-white/10"><div className="max-w-7xl mx-auto px-5 lg:px-8 py-5 text-xs text-emerald-200">© 2026 Perpustakaan Desa Lasem. Melayani dengan literasi.</div></div></footer>
  </div>;
}
