import React, { useMemo, useState } from 'react';
import { BookOpen, Search, Home, Compass, Bookmark, Settings, UserRound, Moon, Bell, ChevronRight, Star } from 'lucide-react';
import { Book } from '../types';

interface Props { books: Book[]; onSelectBook:(b:Book)=>void; onSearchFocus:()=>void; onReadBook:(b:Book)=>void; onNavigate?:(tab:string)=>void; onLogout?:()=>void; }

export const TargetHomeTab: React.FC<Props> = ({ books, onSelectBook, onSearchFocus, onReadBook, onNavigate, onLogout }) => {
  const [activeTab, setActiveTab] = useState<'Popular'|'Top Selling'|'Following'|'New'>('Popular');
  const featured = useMemo(() => {
    if (activeTab === 'New') return [...books].sort((a,b) => b.year-a.year).slice(0,10);
    if (activeTab === 'Top Selling') return [...books].sort((a,b) => Number(b.isPopular)-Number(a.isPopular) || b.rating-a.rating).slice(0,10);
    if (activeTab === 'Following') return books.filter(b => b.category === 'Edukasi' || b.category === 'Budaya Desa').slice(0,10);
    return books.slice(0,10);
  }, [books, activeTab]);
  const authors = Array.from(new Set(books.map(b=>b.author))).slice(0,5);
  const card = (book:Book) => <button key={book.id} onClick={()=>onSelectBook(book)} className="text-left group min-w-0"><div className="aspect-[3/4] rounded-xl overflow-hidden bg-slate-100 shadow-sm"><img src={book.coverImage} alt={book.title} className="w-full h-full object-cover group-hover:scale-105 transition" referrerPolicy="no-referrer" /></div><div className="mt-2 text-sm font-semibold text-slate-800 truncate">{book.title}</div><div className="text-xs text-slate-500 truncate">{book.author}</div><div className="flex items-center gap-1 mt-1 text-[11px] text-amber-600"><Star className="w-3 h-3 fill-current"/>{book.rating.toFixed(1)}<span className="text-slate-400">• {book.category}</span></div></button>;
  return <div className="min-h-screen bg-[#f7f9fd] text-slate-800">
    <aside className="hidden lg:flex fixed inset-y-0 left-0 w-56 bg-white border-r border-slate-100 p-7 flex-col z-20"><div className="flex items-center gap-3 text-xl font-bold mb-14"><span className="w-10 h-10 rounded-xl bg-emerald-700 text-white grid place-items-center"><BookOpen className="w-5 h-5"/></span><span>SIMPUL<br/><span className="text-emerald-700">LITERASI</span></span></div><nav className="space-y-3 text-sm"><button className="w-full flex items-center gap-3 rounded-xl bg-emerald-50 text-emerald-800 px-4 py-3 font-semibold"><Home className="w-4 h-4"/>Beranda</button><button onClick={onSearchFocus} className="w-full flex items-center gap-3 px-4 py-3 text-slate-500"><Compass className="w-4 h-4"/>Koleksi</button><button onClick={()=>onNavigate?.('borrowing')} className="w-full flex items-center gap-3 px-4 py-3 text-slate-500"><Bookmark className="w-4 h-4"/>Peminjaman</button><button onClick={()=>onNavigate?.('downloads')} className="w-full flex items-center gap-3 px-4 py-3 text-slate-500"><Settings className="w-4 h-4"/>Unduhan</button><button onClick={()=>onNavigate?.('profile')} className="w-full flex items-center gap-3 px-4 py-3 text-slate-500"><UserRound className="w-4 h-4"/>Profil</button></nav></aside>
    <header className="lg:ml-56 h-20 bg-white border-b border-slate-100 flex items-center justify-between px-5 sm:px-10"><button onClick={onSearchFocus} className="flex items-center gap-3 w-64 bg-[#f2f5fd] rounded-xl px-4 py-3 text-sm text-slate-500"><Search className="w-4 h-4"/>Search</button><div className="flex items-center gap-4"><Moon className="w-5 h-5 text-slate-500"/><Bell className="w-5 h-5 text-slate-500"/><button onClick={()=>onNavigate?.('profile')} className="w-9 h-9 rounded-full bg-[#d9c2a2] grid place-items-center"><UserRound className="w-4 h-4 text-white"/></button><button onClick={onLogout} className="text-xs font-semibold text-slate-500 hover:text-rose-700">Keluar</button></div></header>
    <main className="lg:ml-56 p-5 sm:p-8 xl:p-10"><div className="grid grid-cols-1 xl:grid-cols-[minmax(0,1fr)_300px] gap-7"><section className="bg-white rounded-2xl p-5 sm:p-8"><div className="flex items-center gap-2 overflow-x-auto pb-6 text-sm whitespace-nowrap">{(['Popular','Top Selling','Following','New'] as const).map(tab=><button key={tab} onClick={()=>setActiveTab(tab)} className={`rounded-full px-5 py-2 ${activeTab===tab?'bg-emerald-800 text-white':'bg-[#f3f5fa]'}`}>{tab}</button>)}<span className="ml-auto text-emerald-800 font-semibold">Next <ChevronRight className="inline w-4 h-4"/></span></div><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-x-5 gap-y-8">{featured.map(card)}</div><div className="mt-10 space-y-3"><h2 className="text-lg font-bold">Continue Reading</h2>{featured.slice(0,3).map(b=><div key={b.id} className="flex items-center gap-3 bg-[#fafbfe] rounded-xl px-3 py-2"><img src={b.coverImage} alt="" className="w-8 h-10 rounded object-cover"/><span className="text-sm flex-1 truncate">{b.title}</span><div className="w-1/3 h-1.5 bg-slate-200 rounded-full"><div className="w-2/3 h-full bg-emerald-700 rounded-full"/></div><span className="text-xs text-slate-500">64%</span></div>)}</div></section><aside className="hidden xl:block space-y-6"><div className="bg-white rounded-2xl p-6"><h2 className="text-lg font-bold mb-5">Trending Author</h2>{authors.map(a=><div key={a} className="flex items-center gap-3 py-2"><span className="w-9 h-9 rounded-full bg-slate-200 grid place-items-center text-xs font-bold">{a.charAt(0)}</span><span className="text-sm flex-1 truncate">{a}</span><button className="text-xs bg-[#f3f5fa] rounded-lg px-3 py-2">Follow</button></div>)}</div><div className="bg-white rounded-2xl p-6"><h2 className="text-lg font-bold mb-4">Popular Blogs</h2><p className="text-sm font-semibold">The Week All you need to know about</p><p className="text-xs text-slate-500 mt-2">Published by Lasem Sidayu</p><button onClick={()=>featured[0]&&onReadBook(featured[0])} className="mt-5 text-sm text-emerald-800 font-semibold">Read more →</button></div></aside></div></main>
  </div>;
};
