import React, { useMemo, useState } from 'react';
import { Bell, ChevronRight, Moon, Search, Star, UserRound } from 'lucide-react';
import { Book, Announcement } from '../types';

interface Props { books: Book[]; announcements?: Announcement[]; onSelectBook: (book: Book) => void; onSearchFocus: () => void; onReadBook: (book: Book) => void; onNavigate?: (tab: string) => void; onLogout?: () => void; }
type HomeTab = 'Populer' | 'Top Rekomendasi' | 'Mengikuti' | 'Terbaru';

export const TargetHomeTab: React.FC<Props> = ({ books, announcements = [], onSelectBook, onSearchFocus, onReadBook, onNavigate, onLogout }) => {
  const [activeTab, setActiveTab] = useState<HomeTab>('Populer');
  const featured = useMemo(() => {
    if (activeTab === 'Terbaru') return [...books].sort((a, b) => b.year - a.year).slice(0, 10);
    if (activeTab === 'Top Rekomendasi') return [...books].sort((a, b) => Number(b.isFeatured) - Number(a.isFeatured) || Number(b.isPopular) - Number(a.isPopular) || b.rating - a.rating).slice(0, 10);
    if (activeTab === 'Mengikuti') return books.filter((book) => book.category === 'Edukasi' || book.category === 'Budaya Desa').slice(0, 10);
    return books.slice(0, 10);
  }, [books, activeTab]);
  const authors = Array.from(new Set(books.map((book) => book.author))).slice(0, 5);
  const tabs: HomeTab[] = ['Populer', 'Top Rekomendasi', 'Mengikuti', 'Terbaru'];
  return <div className="target-shell min-h-screen bg-[#f7f9fd] text-slate-800">
    <header className="h-20 bg-white border-b border-slate-100 flex items-center justify-between px-5 sm:px-10"><button onClick={onSearchFocus} className="flex items-center gap-3 w-64 bg-[#f2f5fd] rounded-xl px-4 py-3 text-sm text-slate-500"><Search className="w-4 h-4" />Cari koleksi</button><div className="flex items-center gap-4"><Moon className="w-5 h-5 text-slate-500" /><Bell className="w-5 h-5 text-slate-500" /><button onClick={() => onNavigate?.('profile')} className="w-9 h-9 rounded-full bg-[#d9c2a2] grid place-items-center"><UserRound className="w-4 h-4 text-white" /></button><button onClick={onLogout} className="text-xs font-semibold text-slate-500 hover:text-rose-700">Keluar</button></div></header>
    <main className="p-5 sm:p-8 xl:p-10"><div className="grid grid-cols-1 xl:grid-cols-[minmax(0,1fr)_300px] gap-7"><section className="bg-white rounded-2xl p-5 sm:p-8"><div className="flex items-center gap-2 overflow-x-auto pb-6 text-sm whitespace-nowrap">{tabs.map((tab) => <button key={tab} onClick={() => setActiveTab(tab)} className={`rounded-full px-5 py-2 ${activeTab === tab ? 'bg-emerald-800 text-white' : 'bg-[#f3f5fa]'}`}>{tab}</button>)}<span className="ml-auto text-emerald-800 font-semibold">Berikutnya <ChevronRight className="inline w-4 h-4" /></span></div><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-x-5 gap-y-8">{featured.map((book) => <button key={book.id} onClick={() => onSelectBook(book)} className="text-left group min-w-0"><div className="aspect-[3/4] rounded-xl overflow-hidden bg-slate-100 shadow-sm"><img src={book.coverImage} alt={book.title} className="w-full h-full object-cover group-hover:scale-105 transition" referrerPolicy="no-referrer" /></div><div className="mt-2 text-sm font-semibold truncate">{book.title}</div><div className="text-xs text-slate-500 truncate">{book.author}</div><div className="flex items-center gap-1 mt-1 text-[11px] text-amber-600"><Star className="w-3 h-3 fill-current" />{book.rating.toFixed(1)}<span className="text-slate-400">• {book.category}</span></div></button>)}</div><div className="mt-10 space-y-3"><h2 className="text-lg font-bold">Lanjutkan Membaca</h2>{featured.slice(0, 3).map((book) => <div key={book.id} className="flex items-center gap-3 bg-[#fafbfe] rounded-xl px-3 py-2"><img src={book.coverImage} alt="" className="w-8 h-10 rounded object-cover" /><span className="text-sm flex-1 truncate">{book.title}</span><div className="w-1/3 h-1.5 bg-slate-200 rounded-full"><div className="w-2/3 h-full bg-emerald-700 rounded-full" /></div><span className="text-xs text-slate-500">64%</span></div>)}</div></section><aside className="hidden xl:block space-y-6"><div className="bg-white rounded-2xl p-6"><h2 className="text-lg font-bold mb-5">Penulis Populer</h2>{authors.map((author) => <div key={author} className="flex items-center gap-3 py-2"><span className="w-9 h-9 rounded-full bg-slate-200 grid place-items-center text-xs font-bold">{author.charAt(0)}</span><span className="text-sm flex-1 truncate">{author}</span><button className="text-xs bg-[#f3f5fa] rounded-lg px-3 py-2">Ikuti</button></div>)}</div><div className="bg-white rounded-2xl p-6"><h2 className="text-lg font-bold mb-4">Warta Populer</h2><p className="text-sm font-semibold">Pekan literasi Desa Lasem Sidayu</p><p className="text-xs text-slate-500 mt-2">Diterbitkan oleh Perpustakaan Desa Lasem</p><button onClick={() => featured[0] && onReadBook(featured[0])} className="mt-5 text-sm text-emerald-800 font-semibold">Baca selengkapnya →</button></div></aside></div></main>
  </div>;
};
